### ISSUE TITLE
Вибір виду транспорту для подорожі.

### ISSUE THREAD

**Issue by jokur23** [SofiaPyl/-_4#4]
Вибір оптимального варіанту транспорту.

**Comment by SofiaPyl** [comment]
дешевшим у вартості  буде поїзд або електричка

**Comment by jokur23** [comment]
Поїзд,автобус? Можливо в когось є знайомі які допоможуть з транспортом?

**Comment by SofiaPyl** [comment]
нема знайомих

**Comment by jokur23** [comment]
Краще за все буде електричкою.

**Comment by SofiaPyl** [comment]
купуємо квитки кожен окремо зі своїми студентськими для знижки
